name: pwa_dict
description: "Bilingual dictionary app for learning Japanese."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^5.6.7
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.4.0
  json_annotation: ^4.9.0
  kana_kit: ^2.1.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
    - assets/
